version: '3.3'
services:
  webpssm:
    image: sc-registry.fredhutch.org/webpssm:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webpssm.rule=Host(`webpssm.fredhutch.org`)"
        - "traefik.http.routers.webpssm-secured.rule=Host(`webpssm.fredhutch.org`)"
        - "traefik.http.routers.webpssm.entrypoints=web,web-secured"
        - "traefik.http.services.webpssm.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.webpssm.tls=true"

networks:
  sc-swarm-net:
    external: true